### ISSUE TITLE
new purl for MDMC Glossary

### ISSUE THREAD

**Issue by gulzaure** [saidfathalla/PID-Service#58]
### Contact person name

Gulzaure Abdildina

### Contact person email.

gulzaure.abdildina@kit.edu

### Artifact name
 The MDMC-NEP Glossary of Terms
### Overview
TheGlossary of Terms(Glossary hereafter)is a result of the Metadata Working Group[1], which involves members of the “Nanoscience Foundries and FineAnalysis”(NFFA)EUROPE Pilot (NEP) and of the Joint Lab “Integrated Model and Data Driven Materials Characterization” (JL-MDMC) of the Helmholtz Association.

### Reach out
 More contact information: (e.g. website, Git repo, etc)

### What is your artifact prefix?

mng

### Where is the artifact located on the Web (i.e. the URL)?

http://metarepo.nffa.eu:9001/MDMC_NEP_Glossary-1/en/page/

### Do you want to enable content negotiation?

- [X] enable content negotiation

**Comment by gulzaure** [comment]
Hi Said,


The main vocabulary link will be:
https://purls.helmholtz-metadaten.de/evoks/mng/, which should open:
http://metarepo.nffa.eu:9001/MDMC_NEP_Glossary-1/en/

If I want to assign the link to the term it should be https://purls.helmholtz-metadaten.de/evoks/mng/test_term , it should open http://metarepo.nffa.eu:9001/MDMC_NEP_Glossary-1/en/page/test_term.

The same rule as before.

Thanks a lot and with best regards,
Gulzaure

**Comment by gulzaure** [comment]
Hi Said,

could you try again please.

The Vocabulary link: http://metarepo.nffa.eu:9001/MDMC_NEP_Glossary-1/en/

The term link: http://metarepo.nffa.eu:9001/MDMC_NEP_Glossary-1/en/page/testterm

In the terms the last part ‘testterm’ can be changed according to the term ID.

From: Said Fathalla ***@***.***>
Reply to: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Date: Friday, 17. May 2024 at 08:42
To: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Cc: "Abdildina, Gulzaure (SCC)" ***@***.***>, Author ***@***.***>
Subject: Re: [Materials-Data-Science-and-Informatics/PIDA] new purl for MDMC Glossary (Issue #58)


Hi Gulzaure, the provided links are broken

**Comment by gulzaure** [comment]
I think, it is because you can open them only with http without https. Try please to open it with http!

From: Said Fathalla ***@***.***>
Reply to: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Date: Friday, 17. May 2024 at 09:52
To: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Cc: "Abdildina, Gulzaure (SCC)" ***@***.***>, Author ***@***.***>
Subject: Re: [Materials-Data-Science-and-Informatics/PIDA] new purl for MDMC Glossary (Issue #58)


also broken

**Comment by gulzaure** [comment]
I thinks it wokrs only internally via VPN. Could you just create. I will check then if it works or not.

From: Said Fathalla ***@***.***>
Reply to: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Date: Friday, 17. May 2024 at 10:03
To: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Cc: "Abdildina, Gulzaure (SCC)" ***@***.***>, Author ***@***.***>
Subject: Re: [Materials-Data-Science-and-Informatics/PIDA] new purl for MDMC Glossary (Issue #58)


I did both ways. It gives 404.

**Comment by gulzaure** [comment]
Thanks a lot! I think it works. I will try to fix it next week.

From: Said Fathalla ***@***.***>
Reply to: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Date: Friday, 17. May 2024 at 10:54
To: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Cc: "Abdildina, Gulzaure (SCC)" ***@***.***>, Author ***@***.***>
Subject: Re: [Materials-Data-Science-and-Informatics/PIDA] new purl for MDMC Glossary (Issue #58)


We usually do not create PIDs for broken links because this affects the health check of our PIDs, which is coming soon. However, I created it for you now. Please try to fix it asap.

**Comment by hofmannv** [comment]
Hi Gulzaure  - i re-checked all the links that you have provided and have the same issue (HTTP & HTTPS). We are happy to provide a PURL namespace for your resource but of course that makes only sense if the resource is publicly available.

We will wait for you to update us on the availability of the resource... 

best Volker

**Comment by gulzaure** [comment]
Hi Volker,

thank you for the service and support. I was on sick leave, which is why it took a while. But today I handled this task and created a new pull request, which should be accepted 😊. I will write separately to Said.

Thanks and with best regards,
Gulzaure

From: Volker Hofmann ***@***.***>
Reply to: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Date: Saturday, 1. June 2024 at 11:18
To: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Cc: "Abdildina, Gulzaure (SCC)" ***@***.***>, Author ***@***.***>
Subject: Re: [Materials-Data-Science-and-Informatics/PIDA] new purl for MDMC Glossary (Issue #58)


Hi Gulzaure - i re-checked all the links that you have provided and have the same issue (HTTP & HTTPS). We are happy to provide a PURL namespace for your resource but of course that makes only sense if the resource is publicly available.

We will wait for you to update us on the availability of the resource...

best Volker

**Comment by gulzaure** [comment]
Hi Said,

I created a pull request to make the vocabulary publicly available. Could you please review it and merge?

Best,
Gulzaure

From: Said Fathalla ***@***.***>
Reply to: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Date: Friday, 17. May 2024 at 10:54
To: Materials-Data-Science-and-Informatics/PIDA ***@***.***>
Cc: "Abdildina, Gulzaure (SCC)" ***@***.***>, Author ***@***.***>
Subject: Re: [Materials-Data-Science-and-Informatics/PIDA] new purl for MDMC Glossary (Issue #58)


We usually do not create PIDs for broken links because this affects the health check of our PIDs, which is coming soon. However, I created it for you now. Please try to fix it asap.
